### ISSUE TITLE
Possible bug in TCA

### ISSUE THREAD

**Issue by Martin-Vancado** [iundd/a11y_me_video#2]
We encountered a possible bug in the TCA config for column "tx_a11ymevideo_posterimg". The "overrideChildTca" "types" should be assigned through a key. Otherwise this can throw an odd exeption, pointing to the translate viewhelper. 

Our solution was to overwrite the TCA with the "types" key "0" following one single assignment as only the filepallette would be needed here.

```php
    $GLOBALS['TCA']['tt_content']['columns']['tx_a11ymevideo_posterimg']['config']['overrideChildTca']['types'] = [
        '0' => [
            'showitem' => '
                --palette--;;imageoverlayPalette,
                --palette--;;filePalette',
        ],
    ];
```

also see: 
"public/typo3/sysext/core/Documentation/Changelog/7.5/Feature-66371-IntroduceAutoplayOptionForVideoAndAudioFiles.rst".

**Comment by iundd** [comment]
Has been fixed in version 1.0.8. Thank you for your support.
